version: "3.9"
services:
  backend:
    image: "vkmarket_backend:${TAG-latest}"
    env_file:
      - .env
    build:
      context: ./backend

  frontend:
    image: "vkmarket_frontend:${TAG-latest}"
    build:
      context: ./frontend
