version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspace
    env_file:
      - ../../.env
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/pgdata
    env_file:
      - ../../.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  postgres-data:
