version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # монтаж в контейнер всего репозитория (необходимо для работы git)
      - ../..:/workspace
      # т.к пути в venv'е - абсолютные, то при переносе на основную ОС он становится бесполезным
      # поэтому он изолирован
      - venv:/workspace/backend/.venv
    env_file:
      - ../../.env
    environment:
      # необходимо для того, что бы pre-commit не скачивал заново хуки после остановки контейнера
      - PRE_COMMIT_HOME=/workspace/backend/.venv/pre-commit
      - PYTHONPATH=/workspace/backend
    command: sleep infinity

  db:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/pgdata
    env_file:
      - ../../.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  postgres-data:
  venv:
