"""
Пользователи и объявления

Revision ID: 902947644c6c
Revises:
Create Date: 2021-10-23 21:27:28.698637

"""
import sys

import sqlalchemy as sa

from alembic import op

sys.path.append(".")
import app  # noqa

# revision identifiers, used by Alembic.
revision = "902947644c6c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "advert",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("sell", "buy", "service", "performer", name="type"),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "misc",
                "food",
                "clothes",
                "books",
                "electronics",
                "household",
                "furniture",
                name="category",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cost", sa.Integer(), nullable=True),
        sa.Column("semi_free", sa.Boolean(), nullable=False),
        sa.Column("images", sa.ARRAY(sa.String(), dimensions=1), nullable=False),
        sa.Column("views", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_advert_title"), "advert", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_advert_title"), table_name="advert")
    op.drop_table("advert")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
